package dev.operator.core.grammar

/*
 * A small GBNF recogniser for the tests (S6).
 *
 * `:agent-core` has no llama.cpp, so the acceptance test for the per-step grammar cannot ask the
 * sampler. This interprets the *generated* GBNF text directly: it parses the rule set and decides
 * whether a string is in the language, so a test can assert that every valid short-form example for
 * the catalogue is accepted and that a coordinate form is not. Covers the GBNF the slice emits:
 * literals, character classes (with `^` and ranges), rule references, groups, alternation and the
 * `?`, `*`, `+`, `{m}`, `{m,}`, `{m,n}` repetitions.
 */

class GbnfMatcher private constructor(private val rules: Map<String, Expr>, private val root: String) {

    /** True when [input] is generated by the grammar's root rule, end to end. */
    fun accepts(input: String): Boolean {
        val memo = HashMap<Pair<String, Int>, Set<Int>>()
        return matchRef(root, input, 0, memo).contains(input.length)
    }

    fun ruleNames(): Set<String> = rules.keys

    private sealed interface Expr

    private data class Lit(val text: String) : Expr

    private data class Chars(val ranges: List<Pair<Char, Char>>, val negated: Boolean) : Expr

    private data class Ref(val name: String) : Expr

    private data class Seq(val items: List<Expr>) : Expr

    private data class Alt(val items: List<Expr>) : Expr

    private data class Repeat(val inner: Expr, val min: Int, val max: Int?) : Expr

    private fun matchRef(name: String, input: String, pos: Int, memo: HashMap<Pair<String, Int>, Set<Int>>): Set<Int> {
        val rule = rules[name] ?: throw IllegalArgumentException("no rule \"$name\"")
        val key = name to pos
        memo[key]?.let { return it }
        memo[key] = emptySet() // guard against left recursion
        val result = match(rule, input, pos, memo)
        memo[key] = result
        return result
    }

    private fun match(e: Expr, input: String, pos: Int, memo: HashMap<Pair<String, Int>, Set<Int>>): Set<Int> = when (e) {
        is Lit -> if (input.startsWith(e.text, pos)) setOf(pos + e.text.length) else emptySet()
        is Chars -> if (pos < input.length && e.matches(input[pos])) setOf(pos + 1) else emptySet()
        is Ref -> matchRef(e.name, input, pos, memo)
        is Seq -> {
            var positions = setOf(pos)
            for (item in e.items) {
                val next = HashSet<Int>()
                for (p in positions) next.addAll(match(item, input, p, memo))
                positions = next
                if (positions.isEmpty()) break
            }
            positions
        }

        is Alt -> {
            val out = HashSet<Int>()
            for (item in e.items) out.addAll(match(item, input, pos, memo))
            out
        }

        is Repeat -> {
            val out = HashSet<Int>()
            var frontier = setOf(pos)
            var count = 0
            if (count >= e.min) out.add(pos)
            while (frontier.isNotEmpty()) {
                if (e.max != null && count >= e.max) break
                val next = HashSet<Int>()
                for (p in frontier) next.addAll(match(e.inner, input, p, memo))
                count++
                if (count >= e.min) out.addAll(next)
                if (next == frontier) break // the inner matched empty; stop instead of spinning
                frontier = next
            }
            out
        }
    }

    private fun Chars.matches(c: Char): Boolean {
        val inside = ranges.any { c >= it.first && c <= it.second }
        return if (negated) !inside else inside
    }

    companion object {
        private val RULE_HEAD = Regex("""^\s*([A-Za-z_][A-Za-z0-9_-]*)\s*::=\s*(.*)$""")

        fun parse(text: String): GbnfMatcher {
            val ruleTexts = ArrayList<Pair<String, String>>()
            var name: String? = null
            val body = StringBuilder()
            fun flush() {
                if (name != null) ruleTexts.add(name!! to body.toString())
                name = null
                body.setLength(0)
            }
            for (raw in text.lines()) {
                val line = raw.substringBefore('#')
                if (line.isBlank()) continue
                val m = RULE_HEAD.find(line)
                if (m != null) {
                    flush()
                    name = m.groupValues[1]
                    body.append(m.groupValues[2])
                } else {
                    body.append(' ').append(line.trim())
                }
            }
            flush()
            val rules = LinkedHashMap<String, Expr>()
            for ((n, b) in ruleTexts) rules[n] = BodyParser(b).parse()
            val root = ruleTexts.firstOrNull()?.first ?: throw IllegalArgumentException("empty grammar")
            return GbnfMatcher(rules, root)
        }
    }

    private class BodyParser(private val s: String) {
        private var i = 0

        fun parse(): Expr {
            val e = alt()
            skipSpaces()
            require(i >= s.length) { "trailing grammar text: \"${s.substring(i)}\"" }
            return e
        }

        private fun alt(): Expr {
            val items = ArrayList<Expr>()
            items.add(seq())
            skipSpaces()
            while (i < s.length && s[i] == '|') {
                i++
                items.add(seq())
                skipSpaces()
            }
            return if (items.size == 1) items[0] else Alt(items)
        }

        private fun seq(): Expr {
            val items = ArrayList<Expr>()
            while (true) {
                skipSpaces()
                if (i >= s.length || s[i] == '|' || s[i] == ')') break
                items.add(term())
            }
            require(items.isNotEmpty()) { "empty sequence" }
            return if (items.size == 1) items[0] else Seq(items)
        }

        private fun term(): Expr {
            var atom = atom()
            skipSpaces()
            if (i < s.length) {
                when (s[i]) {
                    '?' -> {
                        i++
                        atom = Repeat(atom, 0, 1)
                    }

                    '*' -> {
                        i++
                        atom = Repeat(atom, 0, null)
                    }

                    '+' -> {
                        i++
                        atom = Repeat(atom, 1, null)
                    }

                    '{' -> {
                        i++
                        val min = readInt()
                        var max: Int? = min
                        if (i < s.length && s[i] == ',') {
                            i++
                            max = if (i < s.length && s[i] == '}') null else readInt()
                        }
                        require(i < s.length && s[i] == '}') { "unterminated repetition" }
                        i++
                        atom = Repeat(atom, min, max)
                    }
                }
            }
            return atom
        }

        private fun atom(): Expr {
            skipSpaces()
            require(i < s.length) { "unexpected end of grammar" }
            return when (s[i]) {
                '(' -> {
                    i++
                    val e = alt()
                    skipSpaces()
                    require(i < s.length && s[i] == ')') { "expected ')'" }
                    i++
                    e
                }

                '[' -> parseClass()
                '"' -> Lit(parseString())
                else -> Ref(parseName())
            }
        }

        private fun parseClass(): Chars {
            require(s[i] == '[')
            i++
            var negated = false
            if (i < s.length && s[i] == '^') {
                negated = true
                i++
            }
            val ranges = ArrayList<Pair<Char, Char>>()
            while (i < s.length && s[i] != ']') {
                val lo = parseClassChar()
                if (i + 1 < s.length && s[i] == '-' && s[i + 1] != ']') {
                    i++
                    val hi = parseClassChar()
                    ranges.add(lo to hi)
                } else {
                    ranges.add(lo to lo)
                }
            }
            require(i < s.length && s[i] == ']') { "unterminated character class" }
            i++
            return Chars(ranges, negated)
        }

        private fun parseClassChar(): Char {
            if (s[i] == '\\') {
                i++
                require(i < s.length)
                val c = s[i]
                i++
                return when (c) {
                    'n' -> '\n'
                    't' -> '\t'
                    'r' -> '\r'
                    'x' -> {
                        require(i + 2 <= s.length)
                        val hex = s.substring(i, i + 2)
                        i += 2
                        hex.toInt(16).toChar()
                    }

                    else -> c
                }
            }
            val c = s[i]
            i++
            return c
        }

        private fun parseString(): String {
            require(s[i] == '"')
            i++
            val sb = StringBuilder()
            while (i < s.length && s[i] != '"') {
                if (s[i] == '\\') {
                    i++
                    require(i < s.length)
                    sb.append(
                        when (val c = s[i]) {
                            'n' -> '\n'
                            't' -> '\t'
                            'r' -> '\r'
                            'x' -> {
                                require(i + 3 <= s.length)
                                val hex = s.substring(i + 1, i + 3)
                                i += 2
                                hex.toInt(16).toChar()
                            }

                            else -> c
                        },
                    )
                } else {
                    sb.append(s[i])
                }
                i++
            }
            require(i < s.length && s[i] == '"') { "unterminated string" }
            i++
            return sb.toString()
        }

        private fun parseName(): String {
            val start = i
            while (i < s.length && (s[i].isLetterOrDigit() || s[i] == '_' || s[i] == '-')) i++
            require(i > start) { "expected a grammar name at $i" }
            val name = s.substring(start, i)
            require(name.any { it.isLetter() }) { "a rule name must not be all digits: \"$name\"" }
            return name
        }

        private fun readInt(): Int {
            val start = i
            while (i < s.length && s[i].isDigit()) i++
            require(i > start) { "expected a number" }
            return s.substring(start, i).toInt()
        }

        private fun skipSpaces() {
            while (i < s.length && (s[i] == ' ' || s[i] == '\t')) i++
        }
    }
}
